databases:
  - name: reddit
    databaseName: reddit_i6kh
    user: ngthanhha

services:
  - type: web
    name: reddit
    env: docker
    plan: free
    rootDir: server
    region: singapore
    envVars:
      - key: DATABASE_URL
        value: postgres://ngthanhha:FtDCbGUaw8ivAs2ndyvRUPPtsbaQiT5w@dpg-ch9t3um4dad8g1jaod00-a.singapore-postgres.render.com/reddit_i6kh
      - key: CORS_ORIGIN_PROD
        sync: false
      - key: SESSION_DB_USERNAME_DEV_PROD
        sync: false
      - key: SESSION_DB_PASSWORD_DEV_PROD
        sync: false
      - key: SESSION_SECRET_DEV_PROD
        sync: false
      - key: POOL_MODE
        value: transaction
      - key: SERVER_RESET_QUERY
        value: DISCARD ALL
      - key: MAX_CLIENT_CONN
        value: 500
      - key: DEFAULT_POOL_SIZE
        value: 50
