databases:
  - name: mysite
    databaseName: mysite
    user: mysite

services:
  - type: web
    name: reddit
    env: docker
    plan: free
    rootDir: server
    region: singapore
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: POOL_MODE
        value: transaction
      - key: SERVER_RESET_QUERY
        value: DISCARD ALL
      - key: MAX_CLIENT_CONN
        value: 500
      - key: DEFAULT_POOL_SIZE
        value: 50
