databases:
  - name: Reddit
    databaseName: reddit
    user: ngthanhha
    region: singapore
    plan: free

services:
  - type: web
    name: reddit
    env: docker
    plan: free
    rootDir: server
    region: singapore
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: Reddit
          property: connectionString
      - key: CORS_ORIGIN_PROD
        sync: false
      - key: SESSION_DB_USERNAME_DEV_PROD
        sync: false
      - key: SESSION_DB_PASSWORD_DEV_PROD
        sync: false
      - key: SESSION_SECRET_DEV_PROD
        sync: false
      - key: POOL_MODE
        value: transaction
      - key: SERVER_RESET_QUERY
        value: DISCARD ALL
      - key: MAX_CLIENT_CONN
        value: 500
      - key: DEFAULT_POOL_SIZE
        value: 50
